@echo off
chcp 65001
cmd /c "tweaks\База\Основная оптимизация + приватность Windows 10"
cmd /c "tweaks\База\Вернуть все службы"
cmd /c "tweaks\База\Отключить UAC и smartscreen"
cmd /c "tweaks\База\Windows 10 ALL version activator"
cmd /c "tweaks\База\Основная оптимизация + приватность Windows 11"
cmd /c "tweaks\База\Сделать бэкап служб"
cmd /c "tweaks\База\Обычная перезагрузка"
cmd /c "tweaks\База\Windows 11 ALL version activator"
cmd /c "tweaks\База\Углубленная оптимизация + приватность Windows 10"
cmd /c "tweaks\База\Сделать бэкап как bat"
cmd /c "tweaks\База\Обычная перезагрузка в Безопасный режим"
cmd /c "tweaks\База\Отключить телеметрию Браузеров"
cmd /c "tweaks\База\Углубленная оптимизация + приватность Windows 11"
cmd /c "tweaks\База\Сделать копию реестра от Роджера Роуленда"
cmd /c "tweaks\База\Перезагрузка в Безопасный режим с поддержкой CMD"
cmd /c "tweaks\База\Очистка All Tweaker"
cmd /c "tweaks\База\Хардкорная оптимизация + приватность Windows 10"
cmd /c "tweaks\База\Сделать копию реестра от studfile.net"
cmd /c "tweaks\База\Перезагрузка в Безопасный режим с поддержкой Сети"
cmd /c "tweaks\База\Обновить All Tweaker"
cmd /c "tweaks\База\Хардкорная оптимизация + приватность Windows 11"
cmd /c "tweaks\База\Импортировать копию реестра от studfile.net"
cmd /c "tweaks\База\Windows Vista - Server 2022 Activation"
cmd /c "tweaks\База\Выйти из All Tweaker"
cmd /c "tweaks\Исправление проблем\Вернуть все службы.bat"
cmd /c "tweaks\Исправление проблем\Вернуть все службы.reg"
cmd /c "tweaks\Исправление проблем\Включить обслуживание HDD SSD.bat"
cmd /c "tweaks\Исправление проблем\Запусти если Visual Studio не Устанавливается - Ошибка на этапе загрузки.bat"
cmd /c "tweaks\Исправление проблем\Запусти если Visual Studio не Устанавливается - Ошибка на этапе загрузки.reg"
cmd /c "tweaks\Исправление проблем\Запусти если игры, в которых есть Античит - Не запускаются.bat"
cmd /c "tweaks\Исправление проблем\Запусти если игры, в которых есть Античит - Не запускаются.reg"
cmd /c "tweaks\Исправление проблем\Запусти если медленно открываются проги или игры.bat"
cmd /c "tweaks\Исправление проблем\Запусти если медленно открываются проги или игры.reg"
cmd /c "tweaks\Исправление проблем\Запусти если не запускается GTA V RAGE MP.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работает Bluetooth.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работает Bluetooth.reg"
cmd /c "tweaks\Исправление проблем\Запусти если не работает Store.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работает Store.reg"
cmd /c "tweaks\Исправление проблем\Запусти если не работает VPN.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работает VPN.reg"
cmd /c "tweaks\Исправление проблем\Запусти если не работает Антивирус Винды или Брандмауер.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работает Антивирус Винды или Брандмауер.reg"
cmd /c "tweaks\Исправление проблем\Запусти если не работает буфер WIN + V.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работает дефрагментация.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работает дефрагментация.reg"
cmd /c "tweaks\Исправление проблем\Запусти если не работает или не устанавливается панель Nvidia.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работает или не устанавливается панель Nvidia.reg"
cmd /c "tweaks\Исправление проблем\Запусти если не работает принтер.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работает принтер.reg"
cmd /c "tweaks\Исправление проблем\Запусти если не работает Управление дисками.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работает Управление дисками.reg"
cmd /c "tweaks\Исправление проблем\Запусти если не работают скрипты.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работают скрипты.reg"
cmd /c "tweaks\Исправление проблем\Запусти если не работают уведомления.bat"
cmd /c "tweaks\Исправление проблем\Запусти если не работают уведомления.reg"
cmd /c "tweaks\Исправление проблем\Запусти если поменялся интерфейс окон W7.bat"
cmd /c "tweaks\Исправление проблем\Запусти если поменялся интерфейс окон W7.reg"
cmd /c "tweaks\Исправление проблем\Запусти если пропала иконка Сети - Нельзя зайти в поиск по Wi-Fi.bat"
cmd /c "tweaks\Исправление проблем\Запусти если пропала иконка Сети - Нельзя зайти в поиск по Wi-Fi.reg"
cmd /c "tweaks\Исправление проблем\Запусти если просел ФПС на AMD.bat"
cmd /c "tweaks\Исправление проблем\Запусти если просел ФПС на AMD.reg"
cmd /c "tweaks\Исправление проблем\Запусти если просел ФПС, скачет вар на слабых ПК.ps1"
cmd /c "tweaks\Исправление проблем\Запусти если слетают драйвера после перезагрузки.bat"
cmd /c "tweaks\Исправление проблем\Запусти если слетают драйвера после перезагрузки.reg"
cmd /c "tweaks\Исправление проблем\Запусти если хочешь вернуть функционал горячих клавиш громкости.bat"
cmd /c "tweaks\Исправление проблем\Запусти если хочешь вернуть функционал горячих клавиш громкости.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Desktop tweaks.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Desktop tweaks.reg"
cmd /c "tweaks\Исправление проблем\Отмена\System Responsiveness.bat"
cmd /c "tweaks\Исправление проблем\Отмена\System Responsiveness.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Вернуть все службы.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Вернуть все службы.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Вернуть новое контекстное меню для Windows 11.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Вернуть новое контекстное меню для Windows 11.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Вернуть новое меню электропитании.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Вернуть новое меню электропитании.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить FSO и GameBar.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить FSO и GameBar.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить HDCP для ноутбуков.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить HDCP для ПК.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить SmartSceen и блокировку загрузок.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить SmartSceen и блокировку загрузок.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить Spectre, Meldown, Tsx.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить VBS.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить VBS.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить автообновление.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить автообновление.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить автообновления store.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить автообновления store.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить антивирус Windows.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить антивирус Windows.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить безопасный режим Защитника Windows.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить брандмауер.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить взаимодействие с подключенными пользователями и телеметрию.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить взаимодействие с подключенными пользователями и телеметрию.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить виджеты для Windows 11.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить виджеты для Windows 11.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить гибернацию.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить гибернацию.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить дополнительные ненужные службы.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить дополнительные ненужные службы.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить задачи.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить Защитник (включая исполняемый файл службы защиты от вредоносных программ).bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить Защитник (включая исполняемый файл службы защиты от вредоносных программ).reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить Защитника Windows.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить Защитника Windows.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить исполняемый файл службы защиты от вредоносных программ.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить исполняемый файл службы защиты от вредоносных программ.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить менеджер загрузки карт.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить менеджер загрузки карт.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить нежелательных служб от Adamx.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить обновление Windows.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить обслуживание HDD SSD.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить общий доступ к файлам.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить протокол SMBv1.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить работу программ в фоне для Windows 11.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить работу программ в фоне для Windows 11.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить работу программ в фоне.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить работу программ в фоне.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить сетевого доступа к доменам сбора данных.cmd"
cmd /c "tweaks\Исправление проблем\Отмена\Включить службы Bluetooth.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить службы Bluetooth.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить службы Xbox.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить службы Xbox.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить службы брандмауера.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить службы принтера.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить службы принтера.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить телеметрию Office.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить телеметрию Office.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Включить телеметрию Xbox.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить телеметрию.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить триггеры.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить троттлинг.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Включить троттлинг.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Выключить GameMode.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Выключить GameMode.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Выключить Large System Cache.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Выключить Large System Cache.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Выключить ускоренный ввод с Клавиатуры.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Выключить ускоренный ввод с Клавиатуры.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Дефолт службы win 10 11.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Дефолт службы win 10 11.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Добавить высокую производительность.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Добавить высокую производительность.ps1"
cmd /c "tweaks\Исправление проблем\Отмена\Добавить энергосбережение.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Добавить энергосбережение.ps1"
cmd /c "tweaks\Исправление проблем\Отмена\Если скачет пинг (NetworkThrottling).bat"
cmd /c "tweaks\Исправление проблем\Отмена\Если скачет пинг (NetworkThrottling).reg"
cmd /c "tweaks\Исправление проблем\Отмена\Качество фона 80.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Качество фона 80.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Отменить оптимизацию реестора от EverythingTech.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Отменить оптимизацию реестора от EverythingTech.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Удалить оптимизацию при входе.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Ускорить завершение работы.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Ускорить завершение работы.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\.Дефолт 100.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\.Дефолт 100.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 10.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 10.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 20.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 20.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 30.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 30.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 40.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 40.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 50.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 50.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 60.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 60.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 70.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 70.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 80.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 80.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 90.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size клава\Keyboard Data Queue 90.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\.Дефолт 100.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\.Дефолт 100.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 10.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 10.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 20.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 20.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 30.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 30.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 40.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 40.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 47 (~900 bytes).bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 47 (~900 bytes).reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 50.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 50.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 54 (ios1ph recommended).bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 54 (ios1ph recommended).reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 60.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 60.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 70.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 70.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 80.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 80.reg"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 90.bat"
cmd /c "tweaks\Исправление проблем\Отмена\Data Queue Size мышь\Mouse Data Queue 90.reg"
cmd /c "tweaks\Кастомизация\Вернуть пункт Главная.bat"
cmd /c "tweaks\Кастомизация\Включить секунды в трее.bat"
cmd /c "tweaks\Кастомизация\Включить секунды в трее.reg"
cmd /c "tweaks\Кастомизация\Восстанавливать окна папок.bat"
cmd /c "tweaks\Кастомизация\Восстанавливать окна папок.reg"
cmd /c "tweaks\Кастомизация\Восстановление стрелок с ярлыков.bat"
cmd /c "tweaks\Кастомизация\Восстановление стрелок с ярлыков.reg"
cmd /c "tweaks\Кастомизация\Выключить секунды в трее.bat"
cmd /c "tweaks\Кастомизация\Выключить секунды в трее.reg"
cmd /c "tweaks\Кастомизация\Добавление пункта Быстрый доступ.bat"
cmd /c "tweaks\Кастомизация\Добавление пункта Быстрый доступ.reg"
cmd /c "tweaks\Кастомизация\Отключить ClearType.bat"
cmd /c "tweaks\Кастомизация\Отключить ClearType.reg"
cmd /c "tweaks\Кастомизация\Секретные темы Windows 11.bat"
cmd /c "tweaks\Кастомизация\Секретные темы Windows 11.reg"
cmd /c "tweaks\Кастомизация\Серый цвет выделения.bat"
cmd /c "tweaks\Кастомизация\Серый цвет выделения.reg"
cmd /c "tweaks\Кастомизация\Стандартное мерцание курсора.bat"
cmd /c "tweaks\Кастомизация\Стандартное мерцание курсора.reg"
cmd /c "tweaks\Кастомизация\Стандартные кнопки Свернуть, Развернуть и Закрыть.bat"
cmd /c "tweaks\Кастомизация\Стандартные кнопки Свернуть, Развернуть и Закрыть.reg"
cmd /c "tweaks\Кастомизация\Стандартный цвет выделения.bat"
cmd /c "tweaks\Кастомизация\Стандартный цвет выделения.reg"
cmd /c "tweaks\Кастомизация\Убрать пункт Главная.bat"
cmd /c "tweaks\Кастомизация\Удаление пункта Быстрый доступ.bat"
cmd /c "tweaks\Кастомизация\Удаление пункта Быстрый доступ.reg"
cmd /c "tweaks\Кастомизация\Удаление стрелок с ярлыков.bat"
cmd /c "tweaks\Кастомизация\Удалить дубликаты дисков.bat"
cmd /c "tweaks\Кастомизация\Удалить дубликаты дисков.reg"
cmd /c "tweaks\Кастомизация\Улучшить командную строку.bat"
cmd /c "tweaks\Кастомизация\Улучшить командную строку.reg"
cmd /c "tweaks\Кастомизация\Уменьшить кнопки Свернуть, Развернуть и Закрыть.bat"
cmd /c "tweaks\Кастомизация\Уменьшить кнопки Свернуть, Развернуть и Закрыть.reg"
cmd /c "tweaks\Кастомизация\Ускорение частоты мерцания курсора.bat"
cmd /c "tweaks\Кастомизация\Ускорение частоты мерцания курсора.reg"
cmd /c "tweaks\Кастомизация\Контекстное меню\Командная строка на Рабочем столе.bat"
cmd /c "tweaks\Кастомизация\Контекстное меню\Командная строка на Рабочем столе.reg"
cmd /c "tweaks\Кастомизация\Контекстное меню\Стать владельцем и получить полный доступ - Shift.bat"
cmd /c "tweaks\Кастомизация\Контекстное меню\Стать владельцем и получить полный доступ - Shift.reg"
cmd /c "tweaks\Кастомизация\Контекстное меню\Стать владельцем и получить полный доступ.bat"
cmd /c "tweaks\Кастомизация\Контекстное меню\Стать владельцем и получить полный доступ.reg"
cmd /c "tweaks\Кастомизация\Контекстное меню\Удалить командная строку на Рабочем столе.bat"
cmd /c "tweaks\Кастомизация\Контекстное меню\Удалить командная строку на Рабочем столе.reg"
cmd /c "tweaks\Кастомизация\Контекстное меню\Удалить содержимое папки - Shift.bat"
cmd /c "tweaks\Кастомизация\Контекстное меню\Удалить содержимое папки - Shift.reg"
cmd /c "tweaks\Кастомизация\Контекстное меню\Удалить содержимое папки.bat"
cmd /c "tweaks\Кастомизация\Контекстное меню\Удалить содержимое папки.reg"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Восстановить всё.bat"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Восстановить всё.reg"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Видео.bat"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Видео.reg"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить всё.bat"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить всё.reg"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Документы.bat"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Документы.reg"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Загрузки.bat"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Загрузки.reg"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Изображения.bat"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Изображения.reg"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Музыка.bat"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Музыка.reg"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Объемные объекты.bat"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Объемные объекты.reg"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить папку Объемные объекты.bat"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Рабочий стол.bat"
cmd /c "tweaks\Кастомизация\Удаление папок из Этот компьютер\Удалить Рабочий стол.reg"
cmd /c "tweaks\Обновления\Включить обновления Windows 10.bat"
cmd /c "tweaks\Обновления\Запретить Windows 10 восстановить себя от Windows Update.bat"
cmd /c "tweaks\Обновления\Обновить All Tweaker.bat"
cmd /c "tweaks\Обновления\Обновить Windows без перезагрузки.bat"
cmd /c "tweaks\Обновления\Обновить и перезагрузить Windows.bat"
cmd /c "tweaks\Обновления\Обновление Windows - получать только непосредственно от Microsoft.bat"
cmd /c "tweaks\Обновления\Отключить автоматическое обновление Windows.bat"
cmd /c "tweaks\Обновления\Отключить обновления Windows 10.bat"
cmd /c "tweaks\Обновления\Отключить обновления Windows от ios1ph.bat"
cmd /c "tweaks\Обновления\Отключить службу Windows Update.bat"
cmd /c "tweaks\Обновления\Терапия после обновлений винды.bat"
cmd /c "tweaks\Обновления\Удалить скачанные файлы обновлений Windows.bat"
cmd /c "tweaks\Обновления\Терапия после обновления Windows\Выключить автообновление драйверов.bat"
cmd /c "tweaks\Обновления\Терапия после обновления Windows\Выключить автообновление драйверов.reg"
cmd /c "tweaks\Обновления\Терапия после обновления Windows\Отключить UAC и smartscreen.bat"
cmd /c "tweaks\Обновления\Терапия после обновления Windows\Отключить обновления Windows.bat"
cmd /c "tweaks\Обновления\Терапия после обновления Windows\Отключить оптимизацию доставки.bat"
cmd /c "tweaks\Обновления\Терапия после обновления Windows\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Обновления\Терапия после обновления Windows\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Обновления\Терапия после обновления Windows\Отключить телеметрию и прочую хрень.reg"
cmd /c "tweaks\Обновления\Терапия после обновления Windows\Отключить триггеры.bat"
cmd /c "tweaks\Оптимизация\MartyFiles\Включить зарезервированное хранилище.bat"
cmd /c "tweaks\Оптимизация\MartyFiles\Включить файл гибернации.bat"
cmd /c "tweaks\Оптимизация\MartyFiles\Отключить зарезервированное хранилище.bat"
cmd /c "tweaks\Оптимизация\MartyFiles\Отключить файл гибернации.bat"
cmd /c "tweaks\Оптимизация\MartyFiles\Стандартное мерцание курсора.bat"
cmd /c "tweaks\Оптимизация\MartyFiles\Стандартное мерцание курсора.reg"
cmd /c "tweaks\Оптимизация\MartyFiles\Ускорение частоты мерцания курсора.bat"
cmd /c "tweaks\Оптимизация\MartyFiles\Ускорение частоты мерцания курсора.reg"
cmd /c "tweaks\Оптимизация\MartyFiles\Ускорить запуск Windows.bat"
cmd /c "tweaks\Оптимизация\MartyFiles\Ускорить запуск Windows.reg"
cmd /c "tweaks\Оптимизация\MartyFiles\Ускорить открытие папок.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\W10 Старое меню питании.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\W10 Старое меню питании.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Включить GameMode.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Включить TRIM.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Включить VBS.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Включить VBS.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключение автообновлений драйверов.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключение гибернации.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключение гибернации.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключение залипания клавиш.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключение залипания клавиш.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить FSO и GameBar.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить FSO и GameBar.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить sysmain.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить sysmain.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить автостарт программ.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить прозрачность.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Выключить уведомления защиты.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Максимальная производительность.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Обновить Windows без перезагрузки.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Остановить всю работу в фоне  для Windows 10.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Остановить всю работу в фоне для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Остановить всю работу в фоне для Windows 11.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключение Spectre, Meldown, Tsx.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить HDCP для ноутов.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить HDCP для ПК.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить UAC и smartscreen.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить VBS - W11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить VBS - W11.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить антивирус Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить антивирус Windows.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить брандмауер.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить виджеты для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить виджеты для Windows 11.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить карты.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить оптимизацию доставки.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить телеметрию и прочую хрень.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Открыть параметры быстродействия.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Открыть Электропитание.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Показывать все иконки в трее.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Старое контекстное меню для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Старое контекстное меню для Windows 11.reg"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить высокую производительность.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить скачанные файлы обновлений Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить телеметрию Nvidia.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить энергосбережение.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Autoruns.exe"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Desktop tweaks.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Desktop tweaks.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Keyboard Data Queue 50.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Keyboard Data Queue 50.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Large System Cache.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Large System Cache.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Mouse Data Queue 54 (ios1ph recommended).bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Mouse Data Queue 54 (ios1ph recommended).reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\MSI Mode Tool.exe"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\NetworkThrottling.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\NetworkThrottling.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\System Responsiveness.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\System Responsiveness.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Более жесткая уборка.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Более жесткая уборка.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Выключить службы брандмауера.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Выключить службы брандмауера.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Вырубить обслуживание HDD SSD.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Качество фона 100.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Качество фона 100.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Отключить автообновления store.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Отключить автообновления store.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Отключить обновления Windows.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Отключить триггеры.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Открывать pow файлы.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Открывать pow файлы.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Открыть Электропитание.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Рекомендованные службы 2.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Рекомендованные службы.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Рекомендованные службы.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Сделать бэкап как bat.exe"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Тесты режимов электропитания.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Ускорить завершение работы.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Ускорить завершение работы.reg"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Установить оптимизацию при входе.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\startup\startup.bat"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Amit_v1_lowlatency.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Amit_v2_extreme performance.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Amit_v3_low latency.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Atlas Power Plan.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Bitsum Highest Performance.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Calypto.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\GGOSv0_8_5_Idle_Enabled.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Muren_Idle_Enabled.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Unixcorn_Idle_Enabled.pow"
cmd /c "tweaks\Оптимизация\Углубленная оптимизация\Режимы электропитания\Zoyata_Low Latency.pow"
cmd /c "tweaks\Оптимизация\Хардкор\Выключить службы 2.bat"
cmd /c "tweaks\Оптимизация\Хардкор\Выключить службы.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Отключить устройства разом.bat"
cmd /c "tweaks\Оптимизация\Хардкор\Открывать pow файлы.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Открыть Электропитание.bat"
cmd /c "tweaks\Оптимизация\Хардкор\Смертельная очистка планировщика от AtlasOS.bat"
cmd /c "tweaks\Оптимизация\Хардкор\Тесты режимов электропитания.bat"
cmd /c "tweaks\Оптимизация\Хардкор\devmanview\devmanview.exe"
cmd /c "tweaks\Оптимизация\Хардкор\Адские режимы электропитания\Amit_v1.pow"
cmd /c "tweaks\Оптимизация\Хардкор\Адские режимы электропитания\Amit_v2.pow"
cmd /c "tweaks\Оптимизация\Хардкор\Адские режимы электропитания\Amit_v3.pow"
cmd /c "tweaks\Оптимизация\Хардкор\Адские режимы электропитания\Calypto.pow"
cmd /c "tweaks\Оптимизация\Хардкор\Адские режимы электропитания\GGOSv0_8_5.pow"
cmd /c "tweaks\Оптимизация\Хардкор\Адские режимы электропитания\Muren.pow"
cmd /c "tweaks\Оптимизация\Хардкор\Адские режимы электропитания\RekOS_Power_Plan.pow"
cmd /c "tweaks\Оптимизация\Хардкор\Адские режимы электропитания\Unixcorn.pow"
cmd /c "tweaks\Оптимизация\Хардкор\Адские режимы электропитания\Zoyata.pow"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\+fps.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\12GB.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\14GB.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\16GB.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\24GB.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\2GB.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\2_1.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\2_2.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\2_3.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\2_4.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\32GB.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\4GB.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\64GB.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\6GB.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\8GB.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\Boost FPS 1.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\Boost FPS 2.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\fps boost.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\Game DVR 1.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\Game DVR 2.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\интернет батник.bat"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\Отзывчивость Системы.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\Отключить группировку.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\Сетевой Троттлинг Индекс.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\Системный Приоритет.reg"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\чистка 1.bat"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\чистка 2.bat"
cmd /c "tweaks\Оптимизация\Хардкор\Уменьшить количество svhost и другие твики\чистка 3.bat"
cmd /c "tweaks\Оптимизация YouTube\[Онлайн игры] Запустить сервис GoodbyeDPI.cmd"
cmd /c "tweaks\Оптимизация YouTube\[Онлайн игры] Остановить сервис GoodbyeDPI.cmd"
cmd /c "tweaks\Оптимизация YouTube\Автозапуск (удалить сервис).cmd"
cmd /c "tweaks\Оптимизация YouTube\Автозапуск (установить сервис) для Beeline (Corbina).cmd"
cmd /c "tweaks\Оптимизация YouTube\Автозапуск (установить сервис) для P.a.k.t LLC.cmd"
cmd /c "tweaks\Оптимизация YouTube\Автозапуск (установить сервис) для Park Telecom.cmd"
cmd /c "tweaks\Оптимизация YouTube\Автозапуск (установить сервис) для Sibirskie Seti.cmd"
cmd /c "tweaks\Оптимизация YouTube\Автозапуск (установить сервис) для МГТС.cmd"
cmd /c "tweaks\Оптимизация YouTube\Автозапуск (установить сервис) для Ростелеком (Онлайм).cmd"
cmd /c "tweaks\Оптимизация YouTube\Автозапуск (установить сервис).cmd"
cmd /c "tweaks\Оптимизация YouTube\Запустить GoodbyeDPI (Beeline) (Corbina).cmd"
cmd /c "tweaks\Оптимизация YouTube\Запустить GoodbyeDPI (P.a.k.t LLC).cmd"
cmd /c "tweaks\Оптимизация YouTube\Запустить GoodbyeDPI (Park Telecom).cmd"
cmd /c "tweaks\Оптимизация YouTube\Запустить GoodbyeDPI (Sibirskie Seti).cmd"
cmd /c "tweaks\Оптимизация YouTube\Запустить GoodbyeDPI (МГТС).cmd"
cmd /c "tweaks\Оптимизация YouTube\Запустить GoodbyeDPI (Ростелеком) (Онлайм).cmd"
cmd /c "tweaks\Оптимизация YouTube\Запустить GoodbyeDPI.cmd"
cmd /c "tweaks\Оптимизация YouTube\Запустить Psiphon VPN.bat"
cmd /c "tweaks\Оптимизация YouTube\Изменение DNS на Cloudflare (1.1.1.1 и 1.0.0.1).bat"
cmd /c "tweaks\Оптимизация YouTube\Изменение DNS на Cloudflare (1.1.1.1 и 1.0.0.1).ps1"
cmd /c "tweaks\Оптимизация YouTube\Изменение DNS на Google (8.8.8.8 и 8.8.4.4).bat"
cmd /c "tweaks\Оптимизация YouTube\Изменение DNS на Google (8.8.8.8 и 8.8.4.4).ps1"
cmd /c "tweaks\Оптимизация YouTube\Настройка GoodbyeDPI для работы с браузерами.bat"
cmd /c "tweaks\Оптимизация YouTube\Настройка GoodbyeDPI для работы с браузерами.reg"
cmd /c "tweaks\Оптимизация YouTube\Обновить файл russia-blacklist.cmd"
cmd /c "tweaks\Оптимизация YouTube\Разрешить запуск локальных скриптов PowerShell.bat"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Автозапуск (удалить сервис).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Автозапуск (установить сервис) для Beeline (Corbina).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Автозапуск (установить сервис) для P.a.k.t LLC.cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Автозапуск (установить сервис) для Park Telecom.cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Автозапуск (установить сервис) для Sibirskie Seti.cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Автозапуск (установить сервис) для МГТС.cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Автозапуск (установить сервис) для Ростелеком (Онлайм).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Автозапуск (установить сервис).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Запустить GoodbyeDPI (Beeline) (Corbina).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Запустить GoodbyeDPI (P.a.k.t LLC).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Запустить GoodbyeDPI (Park Telecom).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Запустить GoodbyeDPI (Sibirskie Seti).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Запустить GoodbyeDPI (МГТС).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Запустить GoodbyeDPI (Ростелеком) (Онлайм).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 5)\Запустить GoodbyeDPI.cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Автозапуск (удалить сервис).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Автозапуск (установить сервис) для Beeline (Corbina).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Автозапуск (установить сервис) для P.a.k.t LLC.cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Автозапуск (установить сервис) для Park Telecom.cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Автозапуск (установить сервис) для Sibirskie Seti.cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Автозапуск (установить сервис) для МГТС.cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Автозапуск (установить сервис) для Ростелеком (Онлайм).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Автозапуск (установить сервис).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Запустить GoodbyeDPI (Beeline) (Corbina).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Запустить GoodbyeDPI (P.a.k.t LLC).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Запустить GoodbyeDPI (Park Telecom).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Запустить GoodbyeDPI (Sibirskie Seti).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Запустить GoodbyeDPI (МГТС).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Запустить GoodbyeDPI (Ростелеком) (Онлайм).cmd"
cmd /c "tweaks\Оптимизация YouTube\Alt. version (mode 6)\Запустить GoodbyeDPI.cmd"
cmd /c "tweaks\Оптимизация YouTube\goodbyedpi\x86\goodbyedpi.exe"
cmd /c "tweaks\Оптимизация YouTube\goodbyedpi\x86_64\goodbyedpi.exe"
cmd /c "tweaks\Остальное\Fortnite нормальные приоритеты.bat"
cmd /c "tweaks\Остальное\Fortnite нормальные приоритеты.reg"
cmd /c "tweaks\Остальное\Ultimate Optimization.bat"
cmd /c "tweaks\Остальное\Windows 10 Debloater (Advanced).cmd"
cmd /c "tweaks\Остальное\Windows 10 Debloater.cmd"
cmd /c "tweaks\Остальное\Windows 10 Driver Disabler.cmd"
cmd /c "tweaks\Остальное\Windows 10 Service Disabler.cmd"
cmd /c "tweaks\Остальное\Восстановить счетчики производительности.cmd"
cmd /c "tweaks\Остальное\Выключить автообновление драйверов.bat"
cmd /c "tweaks\Остальное\Выключить автообновление драйверов.reg"
cmd /c "tweaks\Остальное\Выключить прозрачность.reg"
cmd /c "tweaks\Остальное\Выключить режим гибернации.bat"
cmd /c "tweaks\Остальное\Выключить службы.bat"
cmd /c "tweaks\Остальное\Выключить уведомления защиты.reg"
cmd /c "tweaks\Остальное\Глобальное отключение FSO и GameBar.bat"
cmd /c "tweaks\Остальное\Глобальное отключение FSO и GameBar.reg"
cmd /c "tweaks\Остальное\Настройки задержки BCD от Adamx.cmd"
cmd /c "tweaks\Остальное\Оптимизация Windows c Github.bat"
cmd /c "tweaks\Остальное\Оптимизация мыши.bat"
cmd /c "tweaks\Остальное\Оптимизация мыши.reg"
cmd /c "tweaks\Остальное\Оптимизация приоритетов Windows.bat"
cmd /c "tweaks\Остальное\Оптимизация приоритетов Windows.reg"
cmd /c "tweaks\Остальное\Оптимизация редактирования BCD.cmd"
cmd /c "tweaks\Остальное\Оптимизация сети.ps1"
cmd /c "tweaks\Остальное\Оптимизация управления памятью.bat"
cmd /c "tweaks\Остальное\Оптимизация управления памятью.reg"
cmd /c "tweaks\Остальное\Оптимизируйте все настройки Windows от Adamx.bat"
cmd /c "tweaks\Остальное\Оптимизируйте все настройки Windows от Adamx.reg"
cmd /c "tweaks\Остальное\Остановить всю работу в фоне.bat"
cmd /c "tweaks\Остальное\Остановить всю работу в фоне.reg"
cmd /c "tweaks\Остальное\Отключение резерва 20% CPU для фоновых процессов.bat"
cmd /c "tweaks\Остальное\Отключение резерва 20% CPU для фоновых процессов.reg"
cmd /c "tweaks\Остальное\Отключение службы Windows 10.bat"
cmd /c "tweaks\Остальное\Отключите ненужные драйверы Windows 10.bat"
cmd /c "tweaks\Остальное\Отключите ненужные службы.cmd"
cmd /c "tweaks\Остальное\Отключить BitLocker.bat"
cmd /c "tweaks\Остальное\Отключить Ease Of Access.bat"
cmd /c "tweaks\Остальное\Отключить Ease Of Access.reg"
cmd /c "tweaks\Остальное\Отключить Game Bar.bat"
cmd /c "tweaks\Остальное\Отключить Game Bar.reg"
cmd /c "tweaks\Остальное\Отключить Getting Windows ready.bat"
cmd /c "tweaks\Остальное\Отключить HPET, ST_DT.bat"
cmd /c "tweaks\Остальное\Отключить HPET.bat"
cmd /c "tweaks\Остальное\Отключить Защитник Windows.bat"
cmd /c "tweaks\Остальное\Отключить Защитник Windows.reg"
cmd /c "tweaks\Остальное\Отключить отслеживание и телеметрию Windows.bat"
cmd /c "tweaks\Остальное\Отключить отслеживание и телеметрию Windows.reg"
cmd /c "tweaks\Остальное\Отключить полноэкранную оптимизацию Fortnite.bat"
cmd /c "tweaks\Остальное\Отключить полноэкранную оптимизацию Fortnite.reg"
cmd /c "tweaks\Остальное\Отключить предварительную выборку.bat"
cmd /c "tweaks\Остальное\Отключить работу приложений в фоновом режиме.bat"
cmd /c "tweaks\Остальное\Отключить работу приложений в фоновом режиме.reg"
cmd /c "tweaks\Остальное\Отключить регулирование мощности.bat"
cmd /c "tweaks\Остальное\Отключить регулирование мощности.reg"
cmd /c "tweaks\Остальное\Отключить службу менеджера скачанных карт.bat"
cmd /c "tweaks\Остальное\Отключить службы от EverythingTech.cmd"
cmd /c "tweaks\Остальное\Отключить телеметрию Браузеров.cmd"
cmd /c "tweaks\Остальное\Отключить экран блокировки.bat"
cmd /c "tweaks\Остальное\Отключить экран блокировки.reg"
cmd /c "tweaks\Остальное\Отключить эксперименты над ПК.bat"
cmd /c "tweaks\Остальное\Отключить эксперименты над ПК.reg"
cmd /c "tweaks\Остальное\Отобразить скрытые пункты Электропитания.bat"
cmd /c "tweaks\Остальное\Отобразить скрытые пункты Электропитания.reg"
cmd /c "tweaks\Остальное\Полное отключение Центра уведомлений.bat"
cmd /c "tweaks\Остальное\Порог разделения SvcHost.cmd"
cmd /c "tweaks\Остальное\Приватность от Adamx.cmd"
cmd /c "tweaks\Остальное\Приватность от windowser.cmd"
cmd /c "tweaks\Остальное\Проверить сжатие системы.bat"
cmd /c "tweaks\Остальное\Расширенная оптимизация DWM.bat"
cmd /c "tweaks\Остальное\Расширенная оптимизация DWM.reg"
cmd /c "tweaks\Остальное\Расширенная оптимизация GameDVR.bat"
cmd /c "tweaks\Остальное\Расширенная оптимизация GameDVR.reg"
cmd /c "tweaks\Остальное\Регулирование сети.bat"
cmd /c "tweaks\Остальное\Регулирование сети.reg"
cmd /c "tweaks\Остальное\Сжать систему.bat"
cmd /c "tweaks\Остальное\Службы от garbuzilia.bat"
cmd /c "tweaks\Остальное\Службы от garbuzilia.reg"
cmd /c "tweaks\Остальное\Старое меню питании для Windows 10.bat"
cmd /c "tweaks\Остальное\Старое меню питании для Windows 10.reg"
cmd /c "tweaks\Остальное\Твики от garbuzilia.bat"
cmd /c "tweaks\Остальное\Твики от garbuzilia.reg"
cmd /c "tweaks\Остальное\Твики реестора от Adamx.bat"
cmd /c "tweaks\Остальное\Твики реестора от Adamx.reg"
cmd /c "tweaks\Остальное\Твики Реестра от Kazzka.reg"
cmd /c "tweaks\Остальное\Убить DWM.cmd"
cmd /c "tweaks\Остальное\Убрать Input Lag.bat"
cmd /c "tweaks\Остальное\Убрать задержку появления контекстного меню.bat"
cmd /c "tweaks\Остальное\Убрать задержку появления контекстного меню.reg"
cmd /c "tweaks\Остальное\Увеличение системного кэша.bat"
cmd /c "tweaks\Остальное\Увеличение системного кэша.reg"
cmd /c "tweaks\Остальное\Удаление временных файлов и файлов предварительной выборки.cmd"
cmd /c "tweaks\Остальное\Удалить вредоносные UWP приложения.cmd"
cmd /c "tweaks\Остальное\Удалить основные приложения Microsoft.bat"
cmd /c "tweaks\Остальное\Удалить файлы конфигурации Fortnite в Appdata.bat"
cmd /c "tweaks\Остальное\Удалить файлы предварительной выборки.bat"
cmd /c "tweaks\Остальное\Уменьшение времени отключения процессов и показа меню.bat"
cmd /c "tweaks\Остальное\Уменьшение времени отключения процессов и показа меню.reg"
cmd /c "tweaks\Остальное\Уменьшить задержку запуска приложений из автозагрузки.bat"
cmd /c "tweaks\Остальное\Уменьшить задержку запуска приложений из автозагрузки.reg"
cmd /c "tweaks\Остальное\Уменьшить размер файла гибернации.bat"
cmd /c "tweaks\Остальное\Ускорение появления превью на панели задач.bat"
cmd /c "tweaks\Остальное\Ускоренное мерцание курсора.bat"
cmd /c "tweaks\Остальное\Ускорить ввод с Клавиатуры.bat"
cmd /c "tweaks\Остальное\Ускорить ввод с Клавиатуры.reg"
cmd /c "tweaks\Остальное\Ускорить открытие папок.bat"
cmd /c "tweaks\Остальное\qqnwr\Cleanup\Delete Log Files.cmd"
cmd /c "tweaks\Остальное\qqnwr\Cleanup\Delete Temporary Files.cmd"
cmd /c "tweaks\Остальное\qqnwr\Cleanup\Delete Windows Update Cache.cmd"
cmd /c "tweaks\Остальное\qqnwr\CMD Tweaks\3. Remove Power Saving Features On USB Devices.bat"
cmd /c "tweaks\Остальное\qqnwr\CMD Tweaks\4 Disable Memory Compression.cmd"
cmd /c "tweaks\Остальное\qqnwr\CMD Tweaks\6 Turn Off Auto Windows Updates.cmd"
cmd /c "tweaks\Остальное\qqnwr\CMD Tweaks\Disable HIPM _ DIPM, HDD Parking.bat"
cmd /c "tweaks\Остальное\qqnwr\CMD Tweaks\Disable IoLatencyCap.bat"
cmd /c "tweaks\Остальное\qqnwr\CMD Tweaks\Disable StorPort Idle.bat"
cmd /c "tweaks\Остальное\qqnwr\CMD Tweaks\Disable USB Idle.bat"
cmd /c "tweaks\Остальное\qqnwr\CMD Tweaks\FSE and Game Bar off.bat"
cmd /c "tweaks\Остальное\qqnwr\CMD Tweaks\Latency Tweaks.cmd"
cmd /c "tweaks\Остальное\qqnwr\fix mouse\Mouse Optimizations.reg"
cmd /c "tweaks\Остальное\qqnwr\fix mouse\MouseFix - Default.reg"
cmd /c "tweaks\Остальное\qqnwr\fix mouse\MouseFix.reg"
cmd /c "tweaks\Остальное\qqnwr\fix mouse\макс отклик.reg"
cmd /c "tweaks\Остальное\qqnwr\Keyboard_Mouse\10decimal\KBDQS 10.reg"
cmd /c "tweaks\Остальное\qqnwr\Keyboard_Mouse\10decimal\MDQS 10 .reg"
cmd /c "tweaks\Остальное\qqnwr\Keyboard_Mouse\16decimal\KBDQS 16.reg"
cmd /c "tweaks\Остальное\qqnwr\Keyboard_Mouse\16decimal\MDQS 16.reg"
cmd /c "tweaks\Остальное\qqnwr\Ram Tweaks\1. Memory Management Optimizations (Credit EverythingTech).reg"
cmd /c "tweaks\Остальное\qqnwr\Ram Tweaks\12GB Ram.reg"
cmd /c "tweaks\Остальное\qqnwr\Ram Tweaks\16GB Ram.reg"
cmd /c "tweaks\Остальное\qqnwr\Ram Tweaks\2. Disable LargeSystemCache.reg"
cmd /c "tweaks\Остальное\qqnwr\Ram Tweaks\32GB Ram.reg"
cmd /c "tweaks\Остальное\qqnwr\Ram Tweaks\4GB Ram.reg"
cmd /c "tweaks\Остальное\qqnwr\Ram Tweaks\6GB Ram.reg"
cmd /c "tweaks\Остальное\qqnwr\Ram Tweaks\8GB Ram.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\1. Registry Tweaks.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\2. Extra Registry Tweaks.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\3 Disable Spectre _ Meltdown Windows Patches.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\5 Disable UAC.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\8. Disable File History Service.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\9. Large system cache.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Decrease Delay.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\DmaRemapping.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Exclusive_Fullscreen.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\High Priority Fortnite.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\LowLatencyScaling.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Optimize ALL Windows Settings.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Prioritys.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Transactional Synchronization Extensions.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\USB Suspend Disable.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\CSRSS\Default CSRSS Priority.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\CSRSS\Tweaked CSRSS Priority.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Might be good\Default lsass Priority.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Might be good\Default winlogon Priority.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Might be good\Tweaked lsass Priority.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Might be good\Tweaked winlogon Priority.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Win32\26HEXWindows32PrioritySeperation.reg"
cmd /c "tweaks\Остальное\qqnwr\Registry Tweaks\Win32\36HEXWindows32priorityseperation.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\Отключение нежелательных служб от Adamx.bat"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\Отключите дополнительные ненужные службы.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\Отключить взаимодействие с подключенными пользователями и телеметрию.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\Отключить исполняемый файл службы защиты от вредоносных программ.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\Отключить менеджер загрузки карт.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\Отключить службы Bluetooth.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\Отключить службы Xbox.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\Отключить службы принтера.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\# Revert Folder\Отменить - Отключите дополнительные ненужные службы.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\# Revert Folder\Отменить - Отключить взаимодействие с подключенными пользователями и телеметрию.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\# Revert Folder\Отменить - Отключить исполняемый файл службы защиты от вредоносных программ.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\# Revert Folder\Отменить - Отключить менеджер загрузки карт.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\# Revert Folder\Отменить - Отключить нежелательных служб от Adamx.bat"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\# Revert Folder\Отменить - Отключить службы Bluetooth.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\# Revert Folder\Отменить - Отключить службы Xbox.reg"
cmd /c "tweaks\Остальное\qqnwr\Unwanted Services\# Revert Folder\Отменить - Отключить службы принтера.reg"
cmd /c "tweaks\Остальное\qqnwr\Windows10Debloater-master\Windows10Debloater.ps1"
cmd /c "tweaks\Остальное\qqnwr\Windows10Debloater-master\Windows10DebloaterGUI.ps1"
cmd /c "tweaks\Остальное\qqnwr\Windows10Debloater-master\Windows10SysPrepDebloater.ps1"
cmd /c "tweaks\Остальное\qqnwr\Windows10Debloater-master\Individual Scripts\Clear Last Used Files and Folders.ps1"
cmd /c "tweaks\Остальное\qqnwr\Windows10Debloater-master\Individual Scripts\Disable Last Used Files and Folders View.ps1"
cmd /c "tweaks\Остальное\qqnwr\Windows10Debloater-master\Individual Scripts\Set Explorers LaunchTo Computer.ps1"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\Optimize ALL Windows Settings.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• CPU Optimization Pack\Очиститель кэша.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• CPU Optimization Pack\CPU Optimizations\CPU Optimization.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• CPU Optimization Pack\CPU Optimizations\Disable Power Throttling.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• CPU Optimization Pack\CPU Optimizations\Game Optimizations.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• CPU Optimization Pack\CPU Optimizations\Power Optimization.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• File regedit\Disable Power Throttling.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• File regedit\Increase FPS in Games.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• File regedit\Increase Responsiveness.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Command Tweaks\BCD Tweaks.cmd"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Command Tweaks\Disable Process Mitigation.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Command Tweaks\Remove RuntimeBroker.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Command Tweaks\Driver Tweaks\HDD Tweak.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Command Tweaks\Driver Tweaks\SSD Tweak.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Reg Tweaks\Decrease Delay.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Reg Tweaks\Disable GpuEnergyDriver.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Reg Tweaks\Disable Network Throttling.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Reg Tweaks\GPU Tweaks.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Reg Tweaks\Memory Management Optimizations.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• FPS Pack\Reg Tweaks\Monitor Latency Tolerance.reg"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• OpenGLbat\increase_opengl_buffer.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• OpenGLbat\opengl.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• OpenGLbat\opengl2.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• OpenGLbat\OpenGL_buffer (2).bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• OpenGLbat\opengl_buffer.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• OpenGLbat\opengl_buffer_2mb.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• OpenGLbat\opengl_max_buffer_4mb.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Optimization BAT and CMD\1) W10 Отключение HPET.cmd"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Optimization BAT and CMD\3. Remove Power Saving Features On USB Devices.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Optimization BAT and CMD\4 Disable Memory Compression.cmd"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Optimization BAT and CMD\BCDEdit Tweaks.cmd"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Optimization BAT and CMD\Disable HIPM _ DIPM, HDD Parking.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Optimization BAT and CMD\Disable IoLatencyCap.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Optimization BAT and CMD\Disable StorPort Idle.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Optimization BAT and CMD\Disable USB Idle.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Optimization BAT and CMD\FSE and Game Bar off.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Optimization BAT and CMD\Отключить триггеры.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Очистка\1 Delete Temporary Files.bat"
cmd /c "tweaks\Остальное\qqnwr\Оптимизация Windows\• Очистка\2 Disable Prefetch.bat"
cmd /c "tweaks\Остальное\Меньшая задержка ввода и более плавный игровой процесс\16 Hex – самый гладкий.bat"
cmd /c "tweaks\Остальное\Меньшая задержка ввода и более плавный игровой процесс\16 Hex – самый гладкий.reg"
cmd /c "tweaks\Остальное\Меньшая задержка ввода и более плавный игровой процесс\25 Hex – Баланс.bat"
cmd /c "tweaks\Остальное\Меньшая задержка ввода и более плавный игровой процесс\25 Hex – Баланс.reg"
cmd /c "tweaks\Остальное\Меньшая задержка ввода и более плавный игровой процесс\28 Hex — самая низкая задержка ввода.bat"
cmd /c "tweaks\Остальное\Меньшая задержка ввода и более плавный игровой процесс\28 Hex — самая низкая задержка ввода.reg"
cmd /c "tweaks\Остальное\Меньшая задержка ввода и более плавный игровой процесс\По умолчанию — 26 Hex (приоритет программ).bat"
cmd /c "tweaks\Остальное\Меньшая задержка ввода и более плавный игровой процесс\По умолчанию — 26 Hex (приоритет программ).reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Отключить масштабирование дисплея .bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Bluetooth\Включить Bluetooth.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Bluetooth\Отключить Bluetooth (по умолчанию) .bat"
cmd /c "tweaks\Остальное\Твики от Atlas\DSCP\Добавить игру в DSCP Policy.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\EventLog & Taskscheduler\Включить taskscheduler.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\EventLog & Taskscheduler\Включить событие log.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\EventLog & Taskscheduler\Отключить taskscheduler.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\EventLog & Taskscheduler\Отключить событие log.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\FSO & Gamebar\Включить FSO & GameBar.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\HDD\Включить предварительное получение.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\HDD\Отключить предварительное получение.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\IE и WMP\Отключить Internet Explorer.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\IE и WMP\Отключить Windows Media Player.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Largesystemcache\Включить largesystemcache.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Largesystemcache\Отключить largesystemcache (по умолчанию) .reg"
cmd /c "tweaks\Остальное\Твики от Atlas\MMCSS\Включить MMCSS (по умолчанию) .reg"
cmd /c "tweaks\Остальное\Твики от Atlas\MMCSS\Отключить mmcss.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Nvidia\Display Container LS\Включить контейнер на дисплее nvidia ls.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Nvidia\Display Container LS\Отключить контейнер с дисплеем nvidia ls.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Nvidia\Display Container LS\Context Menu\Включить контекстное меню контейнера.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Nvidia\Display Container LS\Context Menu\Отключить контекстное меню контейнера.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Nvidia\Force P-State 0\Nvidia force p-state 0.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Nvidia\Force P-State 0\Вернуть Nvidia Force P-State 0.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\UAC\Включить UAC и связанные с ним услуги.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\UWP\Удалить компоненты xbox.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\UWP\Установите OpenShell (запустите первым) .bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Vcredists\Переустановите vcredists.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\VPN\Включить vpns.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\VPN\Отключить vpns (по умолчанию) .bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Wi-Fi\Disable Wifi.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Wi-Fi\Enable Wifi (default).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Анимация\Включить анимацию.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Анимация\Отключить анимацию (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Бежать с приоритетом\Показать запуск с приоритетом в контекстном меню (по умолчанию).reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Бежать с приоритетом\Удалить запуск с приоритетом в контекстном меню.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Безопасный режим\Безопасный режим с командной строкой.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Безопасный режим\Безопасный режим с сетью.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Безопасный режим\Безопасный режим.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Безопасный режим\Выход Safe Mode.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Брандмауэр\Включить брандмауэр Windows (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Брандмауэр\Отключить брандмауэр Windows.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Быстрый доступ\Показать быстрый доступ.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Быстрый доступ\Удалить быстрый доступ (по умолчанию).reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Власть\Включить iDle (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Власть\Включить состояния сна (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Власть\Отключить idle.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Власть\Отключить состояния сна.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Громкость\Современный объем Floudout (по умолчанию).reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Громкость\Старый объем Freshout.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Данка\Установите размер очереди данных мыши.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Данка\Установить размер очереди данных клавиатуры.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\История буфера обмена и наброски и эскиз\Включить историю буфера обмена.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\История буфера обмена и наброски и эскиз\Отключить историю буфера обмена (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Магазин\Включить магазин (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Магазин\Отключить магазин.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Обнаружение сети\Включить сеть Discovery.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Печать\Включить печать.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Печать\Отключить печать (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Поиск индексации\Включить поиск индексации.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Поиск индексации\Отключить индексацию поиска (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Поиск неисправностей\Включить устранение неполадок.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Поиск неисправностей\Отключить устранение неполадок (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Рабочая станция (SMB)\Включить Lanman Workstation.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Рабочая станция (SMB)\Отключить рабочую станцию ​​Lanman (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Сетевая навигационная панель\Нет сетевой панели (по умолчанию).reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Сетевая навигационная панель\Сетевая панель.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Сеть\Сбросить сеть в Windows default.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Сеть\Сбросить сеть в атлас default.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Сеть\ActiveProbing\Включить ActiveProbing.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Сеть\ActiveProbing\Отключить ActiveProbing (по умолчанию).reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Совместимость против Chate\Включить антишкотежную совместимость.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Совместимость против Chate\Отключить совместимость против Chat (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Стартовое меню\Разблокировать меню Menu.bat.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Стартовое меню\Установите OpenShell (запустите первым) .bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Старый Tab\Современный alt-tab.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Старый Tab\Старый alt-tab (по умолчанию).reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Статический IP\Автоматически установить статический ip.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Уведомления\Включить уведомления.bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Уведомления\Отключить уведомления (по умолчанию).bat"
cmd /c "tweaks\Остальное\Твики от Atlas\Услуги\По умолчанию Atlas Drivers.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Услуги\По умолчанию Atlas Services.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Услуги\По умолчанию Windows Drivers.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Услуги\По умолчанию Windows Services.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Экран блокировки\Show Lockcreen (по умолчанию).reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Экран блокировки\Скрыть блокировку.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Ярлык текст\Восстановить ярлык.reg"
cmd /c "tweaks\Остальное\Твики от Atlas\Ярлык текст\Отключить ярлык (по умолчанию).reg"
cmd /c "tweaks\Очистка\Включить гибернацию.bat"
cmd /c "tweaks\Очистка\Включить зарезервированное хранилище.bat"
cmd /c "tweaks\Очистка\Запуск меню очистки.bat"
cmd /c "tweaks\Очистка\Запуск очистки.bat"
cmd /c "tweaks\Очистка\Отключить гибернацию.bat"
cmd /c "tweaks\Очистка\Отключить зарезервированное хранилище.bat"
cmd /c "tweaks\Очистка\Отменить сжатие системы.bat"
cmd /c "tweaks\Очистка\Очистить Windows v2.0.bat"
cmd /c "tweaks\Очистка\Очистить Windows.bat"
cmd /c "tweaks\Очистка\Очистить автозапуск в реестре.bat"
cmd /c "tweaks\Очистка\Очистить временные файлы и кэш иконок.bat"
cmd /c "tweaks\Очистка\Очистить кэш.bat"
cmd /c "tweaks\Очистка\Очистка All Tweaker.bat"
cmd /c "tweaks\Очистка\Очистка загрузок.bat"
cmd /c "tweaks\Очистка\Очистка и оптимизация дисков.bat"
cmd /c "tweaks\Очистка\Очистка кэша обновлений.bat"
cmd /c "tweaks\Очистка\Очистка от Igromanoff.bat"
cmd /c "tweaks\Очистка\Очистка папок Temp.bat"
cmd /c "tweaks\Очистка\Очистка рабочего стола.bat"
cmd /c "tweaks\Очистка\Очистка файла подкачки.bat"
cmd /c "tweaks\Очистка\Очистка хранилища WinSxS.bat"
cmd /c "tweaks\Очистка\Сбросить счетчик изображений.bat"
cmd /c "tweaks\Очистка\Удалить временные файлы от Adamx.cmd"
cmd /c "tweaks\Очистка\Удалить временные файлы.bat"
cmd /c "tweaks\Очистка\Удалить кеш Центра обновления Windows.cmd"
cmd /c "tweaks\Очистка\Удалить лог файлы.cmd"
cmd /c "tweaks\Очистка\Хардкор чистка 1.bat"
cmd /c "tweaks\Очистка\Хардкор чистка 2.bat"
cmd /c "tweaks\Очистка\Хардкор чистка 3.bat"
cmd /c "tweaks\Поддержка\Бесплатно поддержать автора (зарегаться в sharem по реф. ссылке).bat"
cmd /c "tweaks\Поддержка\Бесплатно поддержать автора (посмотреть рекламу).bat"
cmd /c "tweaks\Поддержка\Поддержать автора (Boosty).bat"
cmd /c "tweaks\Поддержка\Поддержать автора (Т-Банк).bat"
cmd /c "tweaks\Приватность\Telemetry Disabler Ultimate.bat"
cmd /c "tweaks\Приватность\Все твики O&O ShutUp10++.bat"
cmd /c "tweaks\Приватность\Все твики O&O ShutUp10++.reg"
cmd /c "tweaks\Приватность\Отключить новую телеметрию Windows за 2024 год.bat"
cmd /c "tweaks\Приватность\Отключить телеметрию полностью.bat"
cmd /c "tweaks\Приватность\Приватность и отпимизация от Flibustier.bat"
cmd /c "tweaks\Приватность\Приватность и отпимизация от ReviOS.bat"
cmd /c "tweaks\Приватность\Приватность от BoosterX и ios1ph.cmd"
cmd /c "tweaks\Приватность\Приватность от IT-спец. Денис Курец.cmd"
cmd /c "tweaks\Приватность\Приватность от Optimizer.cmd"
cmd /c "tweaks\Приватность\Приватность от Pulse.cmd"
cmd /c "tweaks\Приватность\Приватность от Win 10 Tweaker.cmd"
cmd /c "tweaks\Приватность\Приватность от WPD.bat"
cmd /c "tweaks\Приватность\Приватность от WPD.reg"
cmd /c "tweaks\Приватность\Рекомендуемые и условныетвики O&O ShutUp10++.bat"
cmd /c "tweaks\Приватность\Рекомендуемые и условныетвики O&O ShutUp10++.reg"
cmd /c "tweaks\Приватность\Рекомендуемые твики O&O ShutUp10++.bat"
cmd /c "tweaks\Приватность\Рекомендуемые твики O&O ShutUp10++.reg"
cmd /c "tweaks\Приватность\Удаление файла (CompatTelRunner.exe) телеметрия Windows.bat"
cmd /c "tweaks\Приватность\Удаление файла (mobsync.exe) синхронизация Windows.bat"
cmd /c "tweaks\Приватность\Удалить все приложения Microsoft.bat"
cmd /c "tweaks\Приватность\Удалить протокол SMBv1.bat"
cmd /c "tweaks\Приватность\Adamx\Отключите дополнительные ненужные службы.bat"
cmd /c "tweaks\Приватность\Adamx\Отключите дополнительные ненужные службы.reg"
cmd /c "tweaks\Приватность\Adamx\Отключить SmartSceen и блокировку загрузок.bat"
cmd /c "tweaks\Приватность\Adamx\Отключить SmartSceen и блокировку загрузок.reg"
cmd /c "tweaks\Приватность\Adamx\Отключить взаимодействие с подключенными пользователями и телеметрию.bat"
cmd /c "tweaks\Приватность\Adamx\Отключить взаимодействие с подключенными пользователями и телеметрию.reg"
cmd /c "tweaks\Приватность\Adamx\Отключить Защитник (включая исполняемый файл службы защиты от вредоносных программ).bat"
cmd /c "tweaks\Приватность\Adamx\Отключить Защитник (включая исполняемый файл службы защиты от вредоносных программ).reg"
cmd /c "tweaks\Приватность\Adamx\Отключить исполняемый файл службы защиты от вредоносных программ.bat"
cmd /c "tweaks\Приватность\Adamx\Отключить исполняемый файл службы защиты от вредоносных программ.reg"
cmd /c "tweaks\Приватность\Adamx\Отключить менеджер загрузки карт.bat"
cmd /c "tweaks\Приватность\Adamx\Отключить менеджер загрузки карт.reg"
cmd /c "tweaks\Приватность\Adamx\Отключить службы Bluetooth.bat"
cmd /c "tweaks\Приватность\Adamx\Отключить службы Bluetooth.reg"
cmd /c "tweaks\Приватность\Adamx\Отключить службы Xbox.bat"
cmd /c "tweaks\Приватность\Adamx\Отключить службы Xbox.reg"
cmd /c "tweaks\Приватность\Adamx\Отключить службы диагностики и телеметрии.bat"
cmd /c "tweaks\Приватность\Adamx\Отключить службы диагностики и телеметрии.reg"
cmd /c "tweaks\Приватность\Adamx\Отключить службы принтера.bat"
cmd /c "tweaks\Приватность\Adamx\Отключить службы принтера.reg"
cmd /c "tweaks\Приватность\Adamx\Отключить средство устранения неполадок Центра обновления Windows.cmd"
cmd /c "tweaks\Приватность\Adamx\Принудительно закрыть все процессы и службы(Безопасно).bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Выключить автообновление драйверов.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Выключить автообновление драйверов.reg"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Остановить всю работу в фоне для Windows 10.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Остановить всю работу в фоне для Windows 11.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Остановить всю работу в фоне для Windows 11.reg"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключение Spectre, Meldown, Tsx.reg"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить антивирус Windows.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить антивирус Windows.reg"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить виджеты для Windows 11.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить виджеты для Windows 11.reg"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить карты.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить обновления Windows.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить телеметрию и прочую хрень.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить телеметрию и прочую хрень.reg"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить триггеры.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Удалить телеметрию Nvidia.bat"
cmd /c "tweaks\Приватность\IT-спец. Денис Курец\Отключить Cortana.bat"
cmd /c "tweaks\Приватность\IT-спец. Денис Курец\Отключить Xbox.bat"
cmd /c "tweaks\Приватность\IT-спец. Денис Курец\Отключить другое.bat"
cmd /c "tweaks\Приватность\IT-спец. Денис Курец\Отключить историю.bat"
cmd /c "tweaks\Приватность\IT-спец. Денис Курец\Отключить планы.bat"
cmd /c "tweaks\Приватность\IT-спец. Денис Курец\Отключить сбор.bat"
cmd /c "tweaks\Приватность\IT-спец. Денис Курец\Отключить службы.bat"
cmd /c "tweaks\Приватность\IT-спец. Денис Курец\Отключить телеметрию.bat"
cmd /c "tweaks\Приватность\MartyFiles\Включить Copilot.bat"
cmd /c "tweaks\Приватность\MartyFiles\Включить Copilot.reg"
cmd /c "tweaks\Приватность\MartyFiles\Отключение Cortana.bat"
cmd /c "tweaks\Приватность\MartyFiles\Отключение Cortana.reg"
cmd /c "tweaks\Приватность\MartyFiles\Отключить Defender, SmartScreen и Antimalware.bat"
cmd /c "tweaks\Приватность\MartyFiles\Отключить все типы синхронизыции.bat"
cmd /c "tweaks\Приватность\MartyFiles\Отключить все типы синхронизыции.reg"
cmd /c "tweaks\Приватность\MartyFiles\Отключить сбор данных об установленных приложениях.bat"
cmd /c "tweaks\Приватность\MartyFiles\Отключить сбор данных об установленных приложениях.reg"
cmd /c "tweaks\Приватность\MartyFiles\Отключить эксперименты над ПК.bat"
cmd /c "tweaks\Приватность\MartyFiles\Отключить эксперименты над ПК.reg"
cmd /c "tweaks\Приватность\Optimizer\Отключить Cortana.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить Cortana.reg"
cmd /c "tweaks\Приватность\Optimizer\Отключить «Новости и интересы».bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить «Новости и интересы».reg"
cmd /c "tweaks\Приватность\Optimizer\Отключить безопасный режим Защитника Windows.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить обнаружение Edge.reg"
cmd /c "tweaks\Приватность\Optimizer\Отключить общий доступ к медиаплееру.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить общий доступ к файлам.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить пограничную телеметрию.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить пограничную телеметрию.reg"
cmd /c "tweaks\Приватность\Optimizer\Отключить протокол SMBv1.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить протокол SMBv1.reg"
cmd /c "tweaks\Приватность\Optimizer\Отключить протокол SMBv2.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить протокол SMBv2.reg"
cmd /c "tweaks\Приватность\Optimizer\Отключить рекламу в Проводнике.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить рекламу в Проводнике.reg"
cmd /c "tweaks\Приватность\Optimizer\Отключить телеметрию Office.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить телеметрию Office.reg"
cmd /c "tweaks\Приватность\Optimizer\Отключить телеметрию Visual Studio.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить телеметрию Visual Studio.reg"
cmd /c "tweaks\Приватность\Optimizer\Отключить телеметрию Xbox.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить телеметрию.bat"
cmd /c "tweaks\Приватность\Optimizer\Отключить телеметрию.reg"
cmd /c "tweaks\Приватность\Pulse\Отключить Cortana.bat"
cmd /c "tweaks\Приватность\Pulse\Отключить автоматическое обновление Windows.bat"
cmd /c "tweaks\Приватность\Pulse\Отключить ведение истории поисковых запросов.bat"
cmd /c "tweaks\Приватность\Pulse\Отключить и Xbox сервисы.bat"
cmd /c "tweaks\Приватность\Pulse\Отключить историю для приложений.bat"
cmd /c "tweaks\Приватность\Pulse\Отключить потенциально уязвимые службы.bat"
cmd /c "tweaks\Приватность\Pulse\Отключить сохранение списков последних открытых файлов.bat"
cmd /c "tweaks\Приватность\Pulse\Отключить телеметрию.bat"
cmd /c "tweaks\Приватность\Pulse\Очистка файла подкачки.bat"
cmd /c "tweaks\Приватность\Pulse\Убрать из планировщика запланированные задачи телеметрии.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение «журналирования» Событий Windows.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение «журналирования» Событий Windows.reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение ведения записи поведения пользователя.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение ведения записи поведения пользователя.reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение всех видов телеметрий Office.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение всех видов телеметрий Windows.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение всех типов синхронизаций Windows.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение и выпиливание шпионских модулей Microsoft.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение и выпиливание шпионских модулей Microsoft.reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение определения местоположения пользователя.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение определения местоположения пользователя.reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение проверки обращений через «Обратную связь».bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение проверки обращений через «Обратную связь».reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение рекламного идентификатора и рекламы.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение рекламного идентификатора и рекламы.reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение сбора данных об установленных приложениях.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение сбора данных об установленных приложениях.reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение сбора данных через события планировщика.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение сбора и отправки данных рукописного ввода.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение сбора и отправки данных рукописного ввода.reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение сбора статистики использования приложений.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение сбора статистики использования приложений.reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение сетевого доступа к доменам сбора данных.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение скрытого мониторинга системы.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение скрытого мониторинга системы.reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение скрытого фонового обновления синтеза речи.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение скрытого фонового обновления синтеза речи.reg"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение телеметрии NVIDIA.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение удалённых экспериментов над ПК.bat"
cmd /c "tweaks\Приватность\Win 10 Tweaker\Отключение удалённых экспериментов над ПК.reg"
cmd /c "tweaks\Приватность\windowser\Блокировать нежелательные веб узлы в файл hosts.bat"
cmd /c "tweaks\Приватность\windowser\Блокировка портов (безопасность).bat"
cmd /c "tweaks\Приватность\windowser\Добавление правил брандмауэра. Блокировка нежелательных IP адресов.bat"
cmd /c "tweaks\Приватность\windowser\Отключить биометрическую службу Windows.bat"
cmd /c "tweaks\Приватность\windowser\Отключить все службы Xbox.bat"
cmd /c "tweaks\Приватность\windowser\Отключить камеру.bat"
cmd /c "tweaks\Приватность\windowser\Отключить нежелательные свойства Windows.bat"
cmd /c "tweaks\Приватность\windowser\Отключить обслуживание сенсорной клавиатуры и панели рукописного ввода.bat"
cmd /c "tweaks\Приватность\windowser\Отключить поиск в Windows.bat"
cmd /c "tweaks\Приватность\windowser\Отключить протокол SMB (общий доступ к файлам и принтерам).bat"
cmd /c "tweaks\Приватность\windowser\Отключить розничную демонстрационную услугу.bat"
cmd /c "tweaks\Приватность\windowser\Отключить службу Bluetooth.bat"
cmd /c "tweaks\Приватность\windowser\Отключить службу Windows Update.bat"
cmd /c "tweaks\Приватность\windowser\Отключить службу геолокации.bat"
cmd /c "tweaks\Приватность\windowser\Отключить службу менеджера скачанных карт.bat"
cmd /c "tweaks\Приватность\windowser\Отключить службу общего доступа к проигрывателю Windows Media по сети.bat"
cmd /c "tweaks\Приватность\windowser\Отключить службу помощника по совместимости программ.bat"
cmd /c "tweaks\Приватность\windowser\Отключить службу предварительной оценки Windows.bat"
cmd /c "tweaks\Приватность\windowser\Отключить службу родительского контроля.bat"
cmd /c "tweaks\Приватность\windowser\Отключить службу удаленного реестора.bat"
cmd /c "tweaks\Приватность\windowser\Отключить службу управления корпоративными приложениями.bat"
cmd /c "tweaks\Приватность\windowser\Отключить Центр безопасности.bat"
cmd /c "tweaks\Приватность\windowser\Приватность Windows 10.bat"
cmd /c "tweaks\Приватность\windowser\Удалить шпионские службы от windowser.bat"
cmd /c "tweaks\Приватность\Отключить телеметрию Браузеров\Оптимизировать и удалить телеметрию Google Chrome.bat"
cmd /c "tweaks\Приватность\Отключить телеметрию Браузеров\Отключить телеметрию Microsoft Edge.bat"
cmd /c "tweaks\Приватность\Отключить телеметрию Браузеров\Отключить телеметрию Mozilla Firefox.bat"
cmd /c "tweaks\Приватность\Отключить телеметрию Браузеров\Отключить телеметрию Браузеров.cmd"
cmd /c "tweaks\Приватность\Отключить телеметрию Браузеров\Отключить телеметрию Яндекс Браузера.bat"
cmd /c "tweaks\Программы\Браузеры\Cent Browser.bat"
cmd /c "tweaks\Программы\Браузеры\Thorium.bat"
cmd /c "tweaks\Программы\Игровые платформы\Battle.net.bat"
cmd /c "tweaks\Программы\Игровые платформы\Epic Games Launcher.bat"
cmd /c "tweaks\Программы\Игровые платформы\Origin.bat"
cmd /c "tweaks\Программы\Игровые платформы\Steam.bat"
cmd /c "tweaks\Программы\Игровые платформы\Ubisoft Connect.bat"
cmd /c "tweaks\Программы\Оптимизация\Bulk Crap Uninstaller.bat"
cmd /c "tweaks\Программы\Оптимизация\Dism++.bat"
cmd /c "tweaks\Программы\Оптимизация\Mem Reduct.bat"
cmd /c "tweaks\Программы\Приватность\O&O ShutUp10++.bat"
cmd /c "tweaks\Программы\Приватность\Psiphon VPN.exe"
cmd /c "tweaks\Программы\Приватность\SimpleDnsCrypt.bat"
cmd /c "tweaks\Программы\Приватность\simplewall.bat"
cmd /c "tweaks\Программы\Приватность\smsniff.bat"
cmd /c "tweaks\Программы\Приватность\W10Privacy.bat"
cmd /c "tweaks\Программы\Программы для общения и стриминга\Discord.bat"
cmd /c "tweaks\Программы\Программы для общения и стриминга\OBS Studio.bat"
cmd /c "tweaks\Программы\Программы для общения и стриминга\Twitch.bat"
cmd /c "tweaks\Программы\Твикеры\AncelsPerformanceBatch RUS By Igromanoff.bat"
cmd /c "tweaks\Программы\Твикеры\BoosterX 2.bat"
cmd /c "tweaks\Программы\Твикеры\BoosterX.bat"
cmd /c "tweaks\Программы\Твикеры\Optimizer.bat"
cmd /c "tweaks\Программы\Твикеры\Win 10 Tweaker.bat"
cmd /c "tweaks\Программы\Твикеры\WinCry.bat"
cmd /c "tweaks\Программы\Торрент-клиенты\Deluge.bat"
cmd /c "tweaks\Программы\Торрент-клиенты\qBittorrent.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Возврат приложений от Microsoft.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Отключить Defender, SmartScreen и Antimalware.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить 3D Builder.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Bing Sports.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Cortana.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Groove Music.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Internet Explorer.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Microsoft Edge Appx.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Microsoft Edge и WebView.exe"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Microsoft Edge.exe"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Microsoft Office от Darren White.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Microsoft Office.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Mobile Plans.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить OneDrive.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Paint 3D.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Print 3D.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Windows Defender (DefenderKiller).bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Windows Defender (Fuck Windows Defender).exe"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Windows Defender от MartyFiles.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Windows Defender от Vlado.exe"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Xbox App.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Xbox Bar.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Xbox Game Speech.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Будильники и часы.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Ваш телефон.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Деньги.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Записки.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Запись голоса.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить и другие приложения Metro.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Калькулятор.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Камера.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Карты.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Кино и ТВ.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Люди.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Набросок на фрагменте экрана.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Начало.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить основные приложения Microsoft.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Портал смешанной реальности.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Почта и Календарь.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Расширение для изображений HEIF.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Расширение для изображений Webp.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Расширение для интернет-мультимедиа.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Советы.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить средство 3D-просмотра.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Техническая помощь.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Фотографии (Майкрософт).ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Центр отзывов.ps1"
cmd /c "tweaks\Электропитание\Adamx's Power Plan.pow"
cmd /c "tweaks\Электропитание\Adamx.pow"
cmd /c "tweaks\Электропитание\Alchemy.pow"
cmd /c "tweaks\Электропитание\Amit.pow"
cmd /c "tweaks\Электропитание\Amit_v1.pow"
cmd /c "tweaks\Электропитание\Amit_v1_lowlatency.pow"
cmd /c "tweaks\Электропитание\Amit_v2.pow"
cmd /c "tweaks\Электропитание\Amit_v2_extreme performance.pow"
cmd /c "tweaks\Электропитание\Amit_v3.pow"
cmd /c "tweaks\Электропитание\Amit_v3_low latency.pow"
cmd /c "tweaks\Электропитание\Anti Lag.pow"
cmd /c "tweaks\Электропитание\Atlas Power Plan.pow"
cmd /c "tweaks\Электропитание\Balanced.pow"
cmd /c "tweaks\Электропитание\Bitsum Highest Performance.pow"
cmd /c "tweaks\Электропитание\Bitsum_Highest_Performance.pow"
cmd /c "tweaks\Электропитание\Calypto.pow"
cmd /c "tweaks\Электропитание\Calyptos_Low_Latency.pow"
cmd /c "tweaks\Электропитание\Core.pow"
cmd /c "tweaks\Электропитание\CPU-MaxPower.pow"
cmd /c "tweaks\Электропитание\DraganOS.pow"
cmd /c "tweaks\Электропитание\GGOSv0_8_5.pow"
cmd /c "tweaks\Электропитание\GGOSv0_8_5_Idle_Enabled.pow"
cmd /c "tweaks\Электропитание\High Peformance.pow"
cmd /c "tweaks\Электропитание\Igromanoff v1.pow"
cmd /c "tweaks\Электропитание\igromanoff v2.pow"
cmd /c "tweaks\Электропитание\Khorvie.pow"
cmd /c "tweaks\Электропитание\max perfomance.pow"
cmd /c "tweaks\Электропитание\Muren.pow"
cmd /c "tweaks\Электропитание\Muren_Idle_Enabled.pow"
cmd /c "tweaks\Электропитание\Power saver.pow"
cmd /c "tweaks\Электропитание\PowerX v1.pow"
cmd /c "tweaks\Электропитание\PowerX v2.pow"
cmd /c "tweaks\Электропитание\PowerX v3.pow"
cmd /c "tweaks\Электропитание\RekOS_Power_Plan.pow"
cmd /c "tweaks\Электропитание\TJxTweaks.pow"
cmd /c "tweaks\Электропитание\Ultra Low Latency Plans.pow"
cmd /c "tweaks\Электропитание\Unixcorn.pow"
cmd /c "tweaks\Электропитание\Unixcorn_Idle_Enabled.pow"
cmd /c "tweaks\Электропитание\Zoyata.pow"
cmd /c "tweaks\Электропитание\Zoyata_Low Latency.pow"
cmd /c "tweaks\Электропитание\Выключение гибернации.bat"
cmd /c "tweaks\Электропитание\Выключение гибернации.reg"
cmd /c "tweaks\Электропитание\Добавить высокую производительность.bat"
cmd /c "tweaks\Электропитание\Добавить энергосбережение.bat"
cmd /c "tweaks\Электропитание\Максимальная производительность.bat"
cmd /c "tweaks\Электропитание\Открывать pow файлы.bat"
cmd /c "tweaks\Электропитание\Открывать pow файлы.reg"
cmd /c "tweaks\Электропитание\Открыть Электропитание.bat"
cmd /c "tweaks\Электропитание\Показывать все иконки в трее.bat"
cmd /c "tweaks\Электропитание\Показывать все иконки в трее.reg"
cmd /c "tweaks\Электропитание\Тесты режимов электропитания.bat"
cmd /c "tweaks\Электропитание\Удалить высокую производительность.bat"
cmd /c "tweaks\Электропитание\Удалить энергосбережение.bat"
cmd /c "tweaks\Электропитание\Программы\PowerSchemeEd\PowerSchemeEd.exe"
cmd /c "tweaks\Электропитание\Программы\PowerSettingsExplorer\PowerSettingsExplorer.exe"
cmd /c "tweaks\Электропитание\Программы\SwitchPowerScheme_v1.3\sPowers.exe"
cmd /c "tweaks\Электропитание\Программы\SwitchPowerScheme_v1.3\sPowers_x64.exe"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Global User Disabled.reg"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Idle Power Mode.reg"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Power Throttling.reg"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Storage D3 In Modern Standby.reg"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Гибернация ssd.bat"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Гибернация ssd.reg"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Глобальный пользователь отключен.bat"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Отключение Энергосбережения USB.ps1"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Регулирование мощности.bat"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Режим ожидания.bat"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Режим сна Диска.bat"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Режим сна Диска.reg"
cmd /c "tweaks\Электропитание\Твики от Igromanoff\Хранилище D3 в современном режиме ожидания.bat"
