@echo off
chcp 65001
cmd /c "tweaks\Поддержка\Бесплатно поддержать автора (зарегаться в sharem по реф. ссылке).bat"
cmd /c "tweaks\Поддержка\Бесплатно поддержать автора (посмотреть рекламу).bat"
cmd /c "tweaks\Поддержка\Поддержать автора (Boosty).bat"
cmd /c "tweaks\Поддержка\Поддержать автора (Т-Банк).bat"
cmd /c "tweaks\База\Основная оптимизация + приватность Windows 10"
cmd /c "tweaks\Приватность\Все твики O&O ShutUp10++.bat"
cmd /c "tweaks\Приватность\Приватность от Optimizer.cmd"
cmd /c "tweaks\Приватность\Удалить все приложения Microsoft.bat"
cmd /c "tweaks\Приватность\Adamx\Отключить менеджер загрузки карт.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Выключить автообновление драйверов.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключение Spectre, Meldown, Tsx.bat"
cmd /c "tweaks\Приватность\BoosterX и ios1ph\Отключить карты.bat"
cmd /c "tweaks\Приватность\Отключить телеметрию Браузеров\Оптимизировать и удалить телеметрию Google Chrome.bat"
cmd /c "tweaks\Приватность\Отключить телеметрию Браузеров\Отключить телеметрию Mozilla Firefox.bat"
cmd /c "tweaks\Приватность\Отключить телеметрию Браузеров\Отключить телеметрию Яндекс Браузера.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Остановить всю работу в фоне  для Windows 11.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Остановить всю работу в фоне  для Windows 10.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить HDCP для ПК.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить антивирус Windows.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить оптимизацию доставки.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Отключить сбор данных в планировщике.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить высокую производительность.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Удалить энергосбережение.bat"
cmd /c "tweaks\Остальное\Оптимизация Windows c Github.bat"
cmd /c "tweaks\Остальное\Оптимизация приоритетов Windows.bat"
cmd /c "tweaks\Остальное\Оптимизация сети.ps1"
cmd /c "tweaks\Остальное\Отключение резерва 20% CPU для фоновых процессов.bat"
cmd /c "tweaks\Остальное\Отключить BitLocker.bat"
cmd /c "tweaks\Остальное\Отключить Game Bar.bat"
cmd /c "tweaks\Остальное\Отключить HPET.bat"
cmd /c "tweaks\Остальное\Удалить вредоносные UWP приложения.cmd"
cmd /c "tweaks\Очистка\Очистить автозапуск в реестре.bat"
cmd /c "tweaks\Очистка\Очистить временные файлы и кэш иконок.bat"
cmd /c "tweaks\Очистка\Очистить кэш.bat"
cmd /c "tweaks\Очистка\Очистка и оптимизация дисков.bat"
cmd /c "tweaks\Очистка\Очистка кэша обновлений.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Отключить Defender, SmartScreen и Antimalware.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить 3D Builder.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Bing Sports.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Cortana.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Groove Music.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Internet Explorer.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Microsoft Edge Appx.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Microsoft Edge и WebView.exe"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Microsoft Edge.exe"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Microsoft Office от Darren White.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Microsoft Office.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Mobile Plans.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить OneDrive.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Paint 3D.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Print 3D.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Windows Defender (DefenderKiller).bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Windows Defender (Fuck Windows Defender).exe"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Windows Defender от MartyFiles.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Windows Defender от Vlado.exe"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Xbox App.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Xbox Bar.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Xbox Game Speech.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Будильники и часы.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Ваш телефон.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Деньги.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Записки.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Запись голоса.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить и другие приложения Metro.bat"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Калькулятор.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Камера.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Карты.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Кино и ТВ.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Люди.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Набросок на фрагменте экрана.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Начало.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить основные приложения Microsoft.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Портал смешанной реальности.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Почта и Календарь.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Расширение для изображений HEIF.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Расширение для изображений Webp.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Расширение для интернет-мультимедиа.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Советы.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить средство 3D-просмотра.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Техническая помощь.ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Фотографии (Майкрософт).ps1"
cmd /c "tweaks\Удалить приложения Microsoft\Удалить Центр отзывов.ps1"
cmd /c "tweaks\Программы\Приватность\O&O ShutUp10++.bat"
cmd /c "tweaks\Программы\Оптимизация\Bulk Crap Uninstaller.bat"
cmd /c "tweaks\Электропитание\Открыть Электропитание.bat"
cmd /c "tweaks\Оптимизация\Основная оптимизация\Открыть параметры быстродействия.bat"
cmd /c "tweaks\Приватность\Telemetry Disabler Ultimate.bat"
cmd /c "tweaks\Оптимизация YouTube\Настройка GoodbyeDPI для работы с браузерами.bat"
cmd /c "tweaks\Оптимизация YouTube\Изменение DNS на Google (8.8.8.8 и 8.8.4.4).bat"
cmd /c "tweaks\Оптимизация YouTube\Запустить GoodbyeDPI.cmd"